Make repo compliant
gardener-attic/ext-authz-server pull request #27
Opened 2024-02-26 12:08 UTC by RaphaelVogel

**What this PR does / why we need it**:
* Updated `CONTRIBUTING.md` file
* Created/Updated `LICENSE` file
* Created/Updated `.reuse/dep5` file
* Created/Updated `LICENSES` folder
* Deleted `NOTICE.md` file
* Added badge for reuse compliance in `README.md` file and registered repo with REUSE API
* License/Copyright header replacement for 'go' files
  * hack/tools.go

2024-02-26 12:20 UTC, DockToFuture approved these changes
/lgtm

2024-02-26 12:20 UTC, ScheererJ requested changes

2024-02-26 12:20 UTC, ScheererJ commented on .reuse/dep5
> +
Why did you add a new line? Are you paid by lines of code?

2024-02-26 12:20 UTC, ScheererJ commented on .reuse/dep5
> +Copyright: 2017-2024 SAP SE or an SAP affiliate company and Gardener contributors
Why do we use a different license for our markdown files compared with the source code?

2024-02-26 12:20 UTC, ScheererJ commented on .reuse/dep5
> +Copyright: 2024 github.com/google/gnostic contributors.
Could you please instead of updating the vendor licenses please create a pull request for vendor folder removal?

/hold

2024-02-26 12:20 UTC, ScheererJ commented on LICENSES/BSD-3-Clause.txt
> +Copyright (c) <year> <owner>.
Why are the rights no longer reserved?

2024-02-26 12:28 UTC, axel7born commented on LICENSES/BSD-3-Clause.txt
> +Copyright (c) <year> <owner>.
The requirement to add the "all rights reserved" notice became essentially obsolete on August 23, 2000, when Nicaragua became the final member of the Buenos Aires Convention to also become a signatory to the Berne Convention.
https://en.wikipedia.org/wiki/All_rights_reserved

2024-03-01 10:02 UTC, ScheererJ commented on .reuse/dep5
> +Copyright: 2024 github.com/google/gnostic contributors.
@RaphaelVogel Please update this pull request as https://github.com/gardener/ext-authz-server/pull/28 has been merged!

2024-03-01 13:49 UTC, closed without merging